Favicons and links
Nihaumi/Shelter-project pull request #13
Opened 2020-02-23 17:42 UTC by Nihaumi

2020-02-25 09:58 UTC, danmoebius requested changes

2020-02-25 09:58 UTC, danmoebius commented on shelter thingy/index.html
> +<<<<<<< HEAD
Hier wurde ein Merge-Konflikt eingecheckt. Bitte nochmal Prüfen.

2020-02-25 09:59 UTC, danmoebius approved these changes

2020-02-25 12:09 UTC, hpa-move requested changes

2020-02-25 12:09 UTC, hpa-move commented on shelter thingy/browserconfig.xml
> +<?xml version="1.0" encoding="utf-8"?>
Gemessen an den eingecheckten Files scheint die Browserconfig unvollständig

2020-02-25 12:09 UTC, hpa-move commented on shelter thingy/html_code.html
> +<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
Hier sind glaube ich nicht alle Files eingebunden.
Sieh dir gern mal https://realfavicongenerator.net/ an

2020-02-25 12:09 UTC, hpa-move commented on shelter thingy/resources/css/BaseRules.css
> +	cursor: pointer;
Ist das notwendig?

2020-02-25 12:09 UTC, hpa-move commented on shelter thingy/resources/css/BaseRules.css
> +.fillViewPortPlease{
Was tut denn die Klasse?
Der Code-Style scheint übrigens immernoch nicht zu passen

2020-02-25 12:09 UTC, hpa-move commented on shelter thingy/resources/css/ModuleRules.css
> +.card-deck {
Allgemein: ich mag die flachen CSS-Scopes! ;)

2020-02-25 12:09 UTC, hpa-move commented on shelter thingy/resources/css/ModuleRules.css
> +.underline:hover:after {
Pseudoklassen bitte immer mit :: selektieren

2020-03-09 15:03 UTC, hpa-move approved these changes

2020-03-09 15:03 UTC, hpa-move commented on shelter thingy/index.html
> +<<<<<<< HEAD
Wenn das behoben ist darfst du mergen

2020-03-09 15:29 UTC, merged