Mobile nav menu
Nihaumi/Shelter-project pull request #14
Opened 2020-02-23 17:43 UTC by Nihaumi

2020-02-25 11:55 UTC, hpa-move requested changes

2020-02-25 11:55 UTC, hpa-move commented on shelter thingy/resources/css/ModuleRules.css
> +.LinkUnderline {
Bitte auf korrekte Schreibweise nach Konvention achten

2020-02-25 11:55 UTC, hpa-move commented on shelter thingy/resources/css/Navbar.css
> +}
Du verwendest hier drei verschiedene Namenschreibweisen. Lass uns da gern mal drüber sprechen ;)

2020-02-25 11:55 UTC, hpa-move commented on shelter thingy/resources/css/ModuleRules.css
> +.LinkUnderline:hover, .LinkUnderline:focus {
Bitte immer nur 1 Statement pro Zeile, da es sind sehr unübersichtlich sein kann

2020-02-25 11:55 UTC, hpa-move commented on shelter thingy/resources/css/ModuleRules.css
> +	background-image: linear-gradient(currentColor, currentColor);
?

2020-03-09 10:25 UTC, Nihaumi commented on shelter thingy/resources/css/ModuleRules.css
> +.LinkUnderline {
hier sind klassennamen geändert

2020-03-09 15:02 UTC, hpa-move approved these changes

2020-03-09 15:15 UTC, merged