Le looks
Nihaumi/Shelter-project pull request #2
Opened 2020-01-20 16:04 UTC by Nihaumi

2020-01-21 07:24 UTC, hpa-move requested changes
Hi Nathalie, lass uns gern mal am Freitag drüber sprechen.

2020-01-21 07:24 UTC, hpa-move commented on shelter thingy/resources/css/BaseRules.css
> +	padding: 0;
Lass uns mal über den Punkt sprechen. Die Abstände einer Standardklasse von Bootstrap global im Projekt zu entfernen fällt einem immer irgendwann auf die Füße ;)
https://getbootstrap.com/docs/4.4/layout/grid/#auto-layout-columns

2020-01-21 07:24 UTC, hpa-move commented on shelter thingy/resources/css/BaseRules.css
> +	padding: 0;
Das betrifft auch die kommenden beiden Blöcke

2020-01-21 07:24 UTC, hpa-move commented on shelter thingy/resources/css/BaseRules.css
> +	font-family: 'Kulim Park', sans-serif;
Ist die Schrift lokal installiert oder auch im Projekt geladen?

2020-01-21 07:24 UTC, hpa-move commented on shelter thingy/resources/css/LayoutRules.css
> +
Das ist auch zu allgemein gefasst, da es tatsächlich auf jedem LI im Projekt greift…

2020-01-24 11:44 UTC, Nihaumi commented on shelter thingy/resources/css/BaseRules.css
> +	font-family: 'Kulim Park', sans-serif;
ist nur als link eingebunden, also wird geladen

2020-02-13 19:21 UTC, merged